ALTER TABLE "Quiz" ADD COLUMN IF NOT EXISTS "thumbnail" TEXT;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "image" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "image" TEXT;
ALTER TABLE "Comment" ADD COLUMN IF NOT EXISTS "image" TEXT;
